[platformio]
default_envs = esp32dev

[env]
platform = espressif32@6.8.1
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^7.0.4

[env:esp32dev]
board = esp32dev
build_flags =
    -DI2S_BCLK_PIN=26
    -DI2S_WS_PIN=25
    -DI2S_DOUT_PIN=22

[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
build_flags =
    -DI2S_BCLK_PIN=16
    -DI2S_WS_PIN=17
    -DI2S_DOUT_PIN=18
